### PR TITLE
Function to check for enforcement version without requiring other libraries

### PR DESCRIPTION
**Pull request by j05u3**
Just in case it helps guys, I am personally using this fork. Sorry if too many PRs.

### CODE REVIEW

**Comment by j05u3** [comment]
Thanks for the stats, I was looking for something like that and couldn't find it. 

It's fine, it was just easier for me as I couldn't find any source telling me Apple will always use the semver standard (they probably will but I couldn't find anything on it).

Regarding the version check, I am doing it because we don't want to lose some earnings until the enforcement (just in the case the user rejects the prompt).

**Comment by untp** [comment]
`version` package is different from `semver`. `semver` requires MAJOR.MINOR.PATCH but `version` package allows MAJOR.MINOR or MAJOR. You can check [tests](https://github.com/dartninja/version/blob/6423ce6b265ca6da274c61cb6481a67168856a30/test/version_test.dart#L238).

Also, this may cause problems with App Store review. Because, Apple rejects apps that don't show the dialog ([1](https://github.com/FirebaseExtended/flutterfire/issues/4271), [2](https://github.com/googleads/googleads-mobile-flutter/issues/100), ...). They may reject your app if the app shows the dialog on 14.5+, not on 14.0-14.5. They may accept it, but you need to test this.

For this PR, I find `isBeingEnforcedInThisVersion` too long. We can use `isEnforced` instead and add `Check authorization is enforced in this iOS version.` to doc. And method call should return bool, not int.

**Comment by j05u3** [comment]
> `version` package is different from `semver`. `semver` requires MAJOR.MINOR.PATCH but `version` package allows MAJOR.MINOR or MAJOR. You can check [tests](https://github.com/dartninja/version/blob/6423ce6b265ca6da274c61cb6481a67168856a30/test/version_test.dart#L238).
> 
> Also, this may cause problems with App Store review. Because, Apple rejects apps that don't show the dialog ([1](https://github.com/FirebaseExtended/flutterfire/issues/4271), [2](https://github.com/googleads/googleads-mobile-flutter/issues/100), ...). They may reject your app if the app shows the dialog on 14.5+, not on 14.0-14.5. They may accept it, but you need to test this.
> 
> For this PR, I find `isBeingEnforcedInThisVersion` too long. We can use `isEnforced` instead and add `Check authorization is enforced in this iOS version.` to doc. And method call should return `Bool(true)` or `Bool(false)`, not `Int(1)` or `Int(0)`.

Thanks for your explanation on semver, I overlooked the specifics.

BTW, I also received the rejection "Please provide us with steps to locate the AppTrackingTransperancy in the app." but the only thing I did was tell them that it only works in 14.5+ and then my update got accepted.

**Comment by untp** [comment]
That is great. I thought Apple was very strict in their policies. It is awesome that they allow requesting dialog only on 14.5+. Thanks for reporting this.

**Pull request closed without merging**
