### PR TITLE
Replaced ocurrences of ios 14 to 14.5 (because apple enforcement starts at 14.5)

### PR DESCRIPTION
**Pull request by j05u3**
I haven't tested it yet. I will update this thread when I do it.

### CODE REVIEW

**Comment by untp** [comment]
What if I want to request tracking authorization on iOS versions between 14.0-14.5? API is available for 14.0+. In 14.5, it is just required to requesting tracking authorization. If you don't want to request tracking authorization on iOS versions between 14.0 and 14.5, you can check with `Platform.operatingSystemVersion`. This library is a wrapper for app tracking transparency API and ATT API is available for iOS 14.0+. So this library should support versions between 14.0-14.5.

**Comment by j05u3** [comment]
> On iOS 14.4, `trackingAuthorizationStatus` returns `notSupported` and `getAdvertisingIdentifier()` returns a string with all zeros.

Thanks so much for testing it. I really didn't expect the `getAdvertisingIdentifier()` to return a string with all zeros on iOS 14.4

**Comment by j05u3** [comment]
Also I didn't know you could ask for ATT permission (I mean actually show the dialog) in pre 14.5 iOS devices.

And also I think you are right, if the ATT library is available, then this flutter library should at least give as the chance to try to use it.

Thanks for checking it out, I will  proceed to close this PR.

**Comment by j05u3** [comment]
I am still wondering if the behavior is the same on real devices. 

[Here](https://developer.apple.com/documentation/adsupport/asidentifiermanager/1614151-advertisingidentifier) it says that the emulator should always receive zeroes (which is wrong per your tests in 14.5), so what else is different from the documentation?

From that article I understand that starting from 14.5+ on real devices the advertisingidentifier will be all zeroes unless the permission was requested and accepted. 

I am still wondering if you can ask for the permission on real devices on 14.x versions prior to 14.5. I am guessing you can, so when the user updates to 14.5 if the permission was previously given we would get a non-zeroes advertisingidentifier

**Comment by untp** [comment]
Oh, my bad. It was a mistake. UUID is always all zeroes on simulator. And you should reopen this PR.

I don't have a real device, so I tested your PR and current stable version on BrowserStack - a real device testing platform. They have a free unlimited plan on open-source projects.

Here are the results: (all tests (except last) performed on iOS 14.0, (I didn't test on 14.5, because BrowserStack doesn't support 14.5))

#### Your PR
No dialogs (because the PR requests on 14.5+) and we can get UUID.
<details><summary>Show image</summary>

pr-14 0

</details>

#### Stable version - Tap Allow (on custom dialog) and Allow (on system dialog)
We can get UUID.
<details><summary>Show image</summary>

orig-14 0-allow-allow

</details>

#### Stable version - Tap Allow (on custom dialog) and Deny (on system dialog)
We can't get UUID. Because we tapped "Ask app not to track" on system dialog.
<details><summary>Show image</summary>

orig-14 0-allow-deny

</details>

#### Stable version - Tap Decide later (on custom dialog)
We can get UUID. This is strange. You can actually get UUID without dialogs.
<details><summary>Show image</summary>

orig-14 0-decidelater

</details>

#### Stable version - Tap Decide later (on custom dialog), then close app and then tap Allow (on custom dialog) and Allow (on system dialog)
This is for testing that can we get same UUID after system dialog.

<details><summary>Show image (after tapping decide later)</summary>

orig-14 0-decidelater-seq

</details>

<details><summary>Show image (app restarted and tapped allow then allow)</summary>

orig-14 0-allow-allow-seq

</details>

#### Stable version - Tap Decide later (on custom dialog), then close app and then tap Allow (on custom dialog) and Deny (on system dialog)
That is awful. We have UUID before dialog, after denying system dialog we can't have UUID.

<details><summary>Show image (after tapping decide later)</summary>

orig-14 0-decidelater-seq2

</details>

<details><summary>Show image (app restarted and tapped allow then Ask app not to track)</summary>

orig-14 0-allow-deny-seq2

</details>

#### Stable version on iOS 13.0
No dialogs and UUID is available.
<details><summary>Show image</summary>

orig-13 0

</details>

**Comment by untp** [comment]
I think this PR should change a bit. Since we can show ATT system dialog on 14.0-14.5, this library should support it. However, we should add a bool parameter (maybe `requestIfRequired`) to library functions for requesting dialog on 14.0+ or 14.5+. If the parameter is true, it will request on 14.5+; else, it will request on 14.0+.

**Comment by j05u3** [comment]
@untp thank you so much for testing it in real devices. I agree with you, we should just check for iOS version for deciding whether to show the dialog or not.

**Pull request closed without merging**
