### PR TITLE
fix: #54, #50 issues

### PR DESCRIPTION
**Pull request by daltoncabrera**
Workaround to bypass: requestTrackingAuthorization call returns immediately with denied value on iOS.

more info: 
https://forums.developer.apple.com/forums/thread/748317

### CODE REVIEW

**Comment by giboin** [comment]
Tested this fix for the issue #50 , it worked for me

tested on iOS 17.4.1 (iPhone 11, real device), with Xcode 15.4

**Comment by JuKu** [comment]
Please merge this, because this solves some major issues with the latest iOS version, where the app tracking transparency library doesn't work.

**Comment by xni06** [comment]
This PR is now 7 weeks old - any reason for the delay?

**Comment by deniza** [comment]
Thank you for the contribution and for addressing the issues #54 and #50. However, I believe that the proposed solution is quite hacky as its nature and implementing this fix directly in the plugin might lead to maintenance challenges and potential issues in the future.

I suggest handling this workaround in the Flutter side of the project. This approach would keep the plugin code cleaner and more maintainable.

**Comment by kentrino** [comment]
@deniza 
The same phenomenon is occurring. The knowledge that `requestTrackingAuthorization` should be called after `didBecomeActiveNotification` is clearly information that the user side shouldn't need to know, and should be encapsulated. We expect the library side to handle this, even if it means using a different solution.

**Comment by JuKu** [comment]
Is there a workaround for this issue?
I need a solution for this ASAP.
Badly, I cannot wait 7 weeks again for a fix.

**Review by deniza — APPROVED** [review]
Thank you so much for your contribution.  🎉

**Comment by deniza** [comment]
@JuKu, @kentrino I just merged the pull request fixing this issue.

**Comment by deniza** [comment]
And by the way, big thanks to @daltoncabrera again for this fix.

**Pull request merged**
