### PR TITLE
feature/rework-platform-condition

### PR DESCRIPTION
**Pull request by EArminjon2**
Actually platform check didn't respect flutter recommandation and block developper to build unit test around it :).

### CODE REVIEW

**Comment by EA-YOUHOU** [comment]
https://github.com/deniza/app_tracking_transparency/issues/30

**Comment by ju851zel** [comment]
Are there any news on this feature, blocking it from being merged?

**Comment by zvikarp** [comment]
@deniza this also fixes a bug where the app crashes if running in an app that supports flutter web. Looking forward for the merge :)

**Comment by deniza** [comment]
Thanks for the contribution and sorry for the huge delay reviewing it.

**Pull request merged**
